### ISSUE TITLE
tcli_out()/tcli_flush()/tcli_clear_screen() - should be exported functions.

### ISSUE THREAD

**Issue by jmcmullan** [dpse/tcli#3]
The following functions are very useful to have exported outside the library, when using a raw UART for output from a command:

```
void tcli_clear_screen(tcli_t *tcli);

void tcli_out(tcli_t *tcli, const char *str);
void tcli_flush(tcli_t *tcli);
```

**Comment by jmcmullan** [comment]
I retract `tcli_out()` and `tcli_flush()` - `tcli_log_*()` is sufficient.

However, `tcli_clear_screen()` would still be useful (say, for a self-refreshing monitoring window)

**Comment by dpse** [comment]
I agree! I need to review and update the API. I also intend to wrap the low-level functions fully so that if the `tclie_*`-functions are used then the `tcli_*`-functions shouldn't have to be touched.

It might actually be a good idea to expose the `out`-function (and va variants) since that could be useful for command implementations if multiple instances are being used at the same time (e.g. with two UARTs, calls to `out` would output directly to the UART from which the command was invoked), Otherwise this has to be handled using the user argument.
