### ISSUE TITLE
feature request: pattern matched commands

### ISSUE THREAD

**Issue by jmcmullan** [dpse/tcli#6]
A feature I've used in past embedded CLI systems was a regularly formed syntax for the command usage description, which the command parser used to determine the validity of arguments.

Here's some examples of the 'usage descriptions':

| Description | Comment |
| --- | --- |
| `reset` | Single word command, must match exactly. |
| `config save` | Two word command, spaces around the words are ignored. |
| `can speed <rate>` | Two word command, with mandatory argument. |
| `set <attr> [value]` | One word command, with mandatory and optional argument. |
| `echo ...` | One word command, with arbitrary number of arguments. |
| `<reg> = <value>` | One word command ('=') embedded between mandatory arguments. | 
| `when <reg> is <value> echo ...` | Three word command, with two mandatory arguments and arbitrary optional. |

The command handler worked just as yours does now, passing in all words in the argument as argc, argv.

The improvements over what you have now is:
* Encourgaing usage document strings along with description
* min_args/max_args can go away (determined when matching the input against the usage string)
* Supports commands embedded between arguments (ie the `<reg> = <value>` case)

**Comment by dpse** [comment]
This would definitively be a nice improvement. It could also be used for automatic tab completion. I guess the question is how complex it should be. Ideally, I would like to support getopts-style arguments and sub-commands but then one might end up with formats such as this:

`command sub-command [-x | --long-x] [-y] [-z<value>] [-a <value> | --long-a <value>] [(-b | -B | --long-b) <value>)] [attr1 <value> | attr1=<value>]  [<attr> <value>]  [<value>]...`

There should also be implicit support for grouping of short arguments (e.g. `-xyb <value>`).

**Comment by jmcmullan** [comment]
A minimal word-token implementation can always be expanded on later to support grouping and option flags.

**Comment by dpse** [comment]
This is now implemented as an optional feature in develop and supports the syntax above and some more stuff except for optionals (`[<attr>]` for optional wildcards, otherwise the match is exact) The pattern matching is also used to provide context-sensitive completions.

I have also included the possibility to add separate options (short and/or long) that can also take patterns (I might change how this is handled because the option patterns can be too greedy, etc.).

The implementation is recursive but stack requirements only depend on pattern complexity.

Your examples above have been added to the demo.
